services:
  mongo:
    image: mongo:8
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - .docker/mongo:/data/db
  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - .docker/redis:/data
