import type { Job } from "bullmq";
import type { JobData, JobResult } from "@/lib/jobs/types.ts";
import type { JobTriggerSource } from "@/lib/jobs/job-registry.ts";
import { EJSON } from "bson";
import { z } from "zod";
import type { Policy } from "@/lib/auth/resources.ts";

/**
 * NetworkCapability - A reusable capability for delegating work to network services
 *
 * This class makes HTTP requests to external services (like Python workers),
 * forwarding the JWT from the environment. The JWT is generated by the parent
 * process (processor.ts) and contains the scoped permissions for this job.
 *
 * Security: Workers using this class cannot issue their own JWTs or escalate
 * privileges. They can only use the JWT provided by the parent process.
 */
export class NetworkJobCapability<
  Input extends Job<JobData> = Job<JobData>,
  Output extends JobResult = JobResult,
> {
  name: string;
  schema: z.ZodType<JobData>;
  policies: Policy[];
  url: string;
  triggers?: {
    sources: JobTriggerSource[];
    debounceMs?: number;
  };
  maxConcurrency?: number;

  constructor(options: {
    name: string;
    schema: z.ZodType<JobData>;
    policies: Policy[];
    url: string;
    triggers?: {
      sources: JobTriggerSource[];
      debounceMs?: number;
    };
    maxConcurrency?: number;
  }) {
    this.name = options.name;
    this.schema = options.schema;
    this.policies = options.policies;
    this.url = options.url;
    this.triggers = options.triggers;
    this.maxConcurrency = options.maxConcurrency;
  }

  get inputSchema() {
    return z.toJSONSchema(this.schema);
  }

  get outputSchema() {
    return { type: "object" };
  }

  getUrl(_input: Input): string {
    return this.url;
  }

  getBody(input: Input): string {
    // Handle both Job objects and raw data
    const jobId = (input as any).id;
    const data = (input as any).data || input;

    return JSON.stringify({
      jobId,
      data: EJSON.serialize(data),
    });
  }

  getMethod(_input: Input): string {
    return "POST";
  }

  getHeaders(_input: Input): Record<string, string> {
    const jwt = Deno.env.get("MYCELIA_JWT");
    if (!jwt) {
      throw new Error("MYCELIA_JWT not found in environment. This worker must be run in an isolated process.");
    }

    return {
      "Content-Type": "application/json",
      "Authorization": `Bearer ${jwt}`,
    };
  }

  async use(input: Input): Promise<Output> {
    const url = this.getUrl(input);
    const response = await fetch(url, {
      method: this.getMethod(input),
      headers: this.getHeaders(input),
      body: this.getBody(input),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `Network capability failed for ${url} (${response.status}): ${errorText}`,
      );
    }
    return response.json();
  }
}
