name: Build and Push Docker Image
on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: mycelia
  IMAGE_TAG: ${{ gitea.sha }}
  PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
  PORTAINER_ENDPOINT_ID: 2
  PORTAINER_SWARM_ID: py11xtob9km7kvehcv0as8yth
  REGISTRY: gitea.tigor.net/tigor

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Gitea Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.PROJECT_NAME }}:latest
      #     cache-to: type=inline
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ env.PROJECT_NAME }}:latest
      #       ${{ env.REGISTRY }}/${{ env.PROJECT_NAME }}:${{ gitea.sha }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Redeploy Stack
        env:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
          PORTAINER_API_KEY: ${{ secrets.PORTAINER_ACCES_TOKEN }}
          GITEA_SHA: ${{ gitea.sha }}
          STACK_NAME: ${{ env.PROJECT_NAME }}
          PORTAINER_ENDPOINT_ID: ${{ env.PORTAINER_ENDPOINT_ID }}
          PORTAINER_SWARM_ID: ${{ env.PORTAINER_SWARM_ID }}
          IMAGE: ${{ env.REGISTRY }}/${{ env.PROJECT_NAME }}:${{ gitea.sha }}
        run: python scripts/redeploy.py
